### ISSUE TITLE
❌ Table check ::error::The output for test Table check did not match%0AExpected:%0A<td>[Zz]

### ISSUE THREAD

**Issue by Elvin-Liu237** [comp426-2022-fall/a01#15]
If you are getting an error message, go through this checklist:

- [ ] Did you search or read through the other issues on this repo to make sure there isn't already a related issue?
- [ ] Have you read the words in the error message to understand their meaning?
- [ ] Have you Googled the words in the error message?
- [ ] Have you searched through the existing issues on this and other COMP 426 repositories to see if someone else identified and worked through the issue?

None of the above, create an issue
------------------------------------------------------------------

Make sure to add **all the information needed to understand the error** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Explain what you are trying to do and what is happening. 
- [ ] Provide the **_command string_** you are trying to run.
- [ ] Provide a **_code snippet_** if you are trying to run some code that you wrote. 
- [ ] Provide **_screenshots_** if applicable.
- [ ] Copy and paste the **_error log_** that shows up in the terminal.
- [ ] What is your **_Node.js version?_** (Run `node -v`.)
- [ ] What is your **_operating system?_** (Run `uname -a` and paste the output.)

Delete text above this line before you submit your issue. Place your issue information in the appropriate sections below.

**Comment by camsimba** [comment]
Hi @Elvin-Liu237 , I see that you solved your issue, but you did not post any information about your problem when making this issue. The point of the issue that you copied into your description is to provide us with more information so that we can better help you through it. Before any of us can help you, you need to properly fill out the issue form, responding to all parts with the proper information.

I am glad that you were able to solve the issue on your own, but be sure that if you make an issue in the future, you report all the information that is requested by the form for us. I will close this issue, but if you still have questions feel free to reopen it or comment on it.
