### ISSUE TITLE
Runtime error: [Table Check]

### ISSUE THREAD

**Issue by s821y9** [comp426-2022-fall/a01#5]
#### What is happening?

The autograder filed at "Run education/autograding@v1"
I get score 37500/50000

#### What does the error say is happening?

::error::The output for test Table check did not match%0AExpected:%0A<td>[Zz]<\/td>%0AActual:%0AServer running at port 43491%0A<!DOCTYPE html>%0A<html lang="en">%0A	<head>  %0A  

#### What do you think the error means?

There is some problem with port.

### Node.js version
 v16.17.0

#### Operating system
Darwin csy.lan 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

**Comment by jdmar3** [comment]
This is absolutely not a problem with the autograder. 

The directions are: 

"Create a new file in the public directory called index.html. Then put the following HTML code in it. _**Add rows to the table below so that there is one row for every letter in the alphabet:**_"

You have not followed the directions.
